name: isda_aqua_gentech
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  lottie: ^3.1.3
  firebase_core: ^3.4.0
  flutter_launcher_icons: ^0.11.0
  geolocator: ^10.0.1
  http: ^1.1.0
  intl: ^0.18.1
  weather_icons: ^3.0.0
  permission_handler: ^11.3.1
  flutter_local_notifications: ^18.0.1
  connectivity_plus: ^6.1.1
  flutter_pdfview: ^1.3.4
  path_provider: ^2.1.4
  share_plus: ^10.0.0
  cloud_firestore: ^5.4.0
  firebase_auth: ^5.2.0
  fluttertoast: ^8.2.8
  google_maps_flutter: ^2.6.1
  philippines_rpcmb: ^0.0.3
  cached_network_image: ^3.2.0
  flutter_svg: ^2.0.10+1
  firebase_storage: ^12.2.0
  shared_preferences: ^2.2.3
  url_launcher: ^6.3.1
  geocoding: ^3.0.0
  location: ^6.0.2
  image_picker: ^0.8.9
  flutter_tflite: ^1.0.1
  flutter_news_service: ^1.0.4
  badges: ^3.1.2
  excel: ^4.0.6
  device_info_plus: ^10.1.2
  open_file: ^3.5.4
  path: ^1.9.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/
    - lib/assets/animations/
    - lib/assets/images/
    - lib/assets/pdfs/
    - lib/assets/weather/
    - lib/models/

flutter_icons:
  android: true
  image_path: "lib/assets/images/primary-logo.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "lib/assets/images/primary-logo.png"