// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwYh5MHDKLKMlphb4lo-qhHkh_Ivxn248',
    appId: '1:1006948485343:web:d848181f832a77af59416a',
    messagingSenderId: '1006948485343',
    projectId: 'isdaaquagentechdb',
    authDomain: 'isdaaquagentechdb.firebaseapp.com',
    storageBucket: 'isdaaquagentechdb.firebasestorage.app',
    measurementId: 'G-E6W2MF336Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJKAKAr2obkmG95Ew0IPJsgaPlO1Myj2Q',
    appId: '1:1006948485343:android:7b064e4773f7ed9159416a',
    messagingSenderId: '1006948485343',
    projectId: 'isdaaquagentechdb',
    storageBucket: 'isdaaquagentechdb.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwYh5MHDKLKMlphb4lo-qhHkh_Ivxn248',
    appId: '1:1006948485343:web:02382c95f92216e259416a',
    messagingSenderId: '1006948485343',
    projectId: 'isdaaquagentechdb',
    authDomain: 'isdaaquagentechdb.firebaseapp.com',
    storageBucket: 'isdaaquagentechdb.firebasestorage.app',
    measurementId: 'G-5RHC2G1XQE',
  );
}
