// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSY0gNdAQrFpLzXTj8VPlZEtLAMhhaeQA',
    appId: '1:224211865301:web:c68900e506730b15365c5c',
    messagingSenderId: '224211865301',
    projectId: 'rescue-moto',
    authDomain: 'rescue-moto.firebaseapp.com',
    databaseURL: 'https://rescue-moto-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'rescue-moto.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBi3AV9SEwbLmuLZNQgG1sXH8az9NTSq-I',
    appId: '1:224211865301:android:fb57abd03b26bdca365c5c',
    messagingSenderId: '224211865301',
    projectId: 'rescue-moto',
    databaseURL: 'https://rescue-moto-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'rescue-moto.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyASeh8IGjmVmbZt2eUj37V58Ahe6hDJ4ow',
    appId: '1:224211865301:web:0378dbe4a93cd1a3365c5c',
    messagingSenderId: '224211865301',
    projectId: 'rescue-moto',
    authDomain: 'rescue-moto.firebaseapp.com',
    databaseURL: 'https://rescue-moto-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'rescue-moto.appspot.com',
  );

}